// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injections

import (
	"github.com/go-playground/validator/v10"
	"github.com/gofiber/fiber/v2"
	"gorm.io/gorm"
	"personal-growth/common/enums"
	"personal-growth/controllers"
	"personal-growth/repositories"
	"personal-growth/routers"
	"personal-growth/services"
)

// Injectors from auth_di.go:

// InitAuth initializes the Auth module using Wire.
func InitAuth(db *gorm.DB) *fiber.App {
	userRepository := ProvideUserRepository(db)
	validate := ProvideValidator()
	authService := ProvideAuthService(userRepository, validate)
	authController := ProvideAuthController(authService)
	app := ProvideAuthRouter(authController, db)
	return app
}

// Injectors from project_di.go:

// InitProject initializes the Project module using Wire.
func InitProject(db *gorm.DB) *fiber.App {
	projectRepository := ProvideProjectRepository(db)
	validate := ProvideValidator()
	projectService := ProvideProjectService(projectRepository, validate)
	projectController := ProvideProjectController(projectService)
	app := ProvideProjectRouter(projectController, db)
	return app
}

// auth_di.go:

// ProvideValidator creates a new validator instance.
func ProvideValidator() *validator.Validate {
	v := validator.New()
	enums.RegisterCustomValidations(v)
	return v
}

// ProvideUserRepository creates a new User repository.
func ProvideUserRepository(db *gorm.DB) repositories.UserRepository {
	return repositories.NewUserRepository(db)
}

// ProvideAuthService creates a new Auth service.
func ProvideAuthService(repo repositories.UserRepository, validate *validator.Validate) services.AuthService {
	return services.NewAuthServiceImpl(repo, validate)
}

// ProvideAuthController creates a new Auth controller.
func ProvideAuthController(service services.AuthService) *controllers.AuthController {
	return controllers.NewAuthController(service)
}

// ProvideAuthRouter creates a new Auth router.
func ProvideAuthRouter(controller *controllers.AuthController, db *gorm.DB) *fiber.App {
	return routers.NewAuthRouter(controller, db)
}

// project_di.go:

// ProvideProjectRepository creates a new Project repository.
func ProvideProjectRepository(db *gorm.DB) repositories.ProjectRepository {
	return repositories.NewProjectRepository(db)
}

// ProvideProjectService creates a new Project service.
func ProvideProjectService(repo repositories.ProjectRepository, validate *validator.Validate) services.ProjectService {
	return services.NewProjectServiceImpl(repo, validate)
}

// ProvideProjectController creates a new Project controller.
func ProvideProjectController(service services.ProjectService) *controllers.ProjectController {
	return controllers.NewProjectController(service)
}

// ProvideProjectRouter creates a new Project router.
func ProvideProjectRouter(controller *controllers.ProjectController, db *gorm.DB) *fiber.App {
	return routers.NewProjectRouter(controller, db)
}
